config/routes.rb
Rails.application.routes.draw do




#顧客用
#URL  /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    scope module: :public do
      root to: "homes#top"
      get 'about' => 'homes#about'
      resources :items, only: [:index, :show]
      resources :customers, only: [:show, :edit, :update]

      resources :cart_items, only: [:index, :update, :create, :destroy]
      resources :orders, only: [:new, :index, :show]
    end







#管理者側
#URL  /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

    namespace :admin do
      get '/' => 'homes#top'
      post 'items' => 'items#create'
      patch 'items/:id' => 'items#update',as: 'edit_item'
      resources :items, only: [:new, :index, :show, :edit]
      resources :customers, only: [:index, :show, :edit, :update]
    end




end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items

  validates :price, presence: true

 ##消費税を求めるメゾッド
  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new    #１つのレコードを新規投稿するため、インスタンス変数は単数形の「@item」にする。
  end


  def create
    @item = Item.new(item_params)
    @item.save                      #投稿された情報を保存する。
    redirect_to admin_items_path(@item.id)    #投稿したものを登録後何処の画面を開くのかを書く。
  end


  def index
    @item = Item.new
    @items = Item.all   #すべてのレコードを取得するので、インスタンス変数は複数形の「@items」になり、「Item.all」=「アイテムのすべて」と書く。
  end


  def show
    @item = Item.find(params[:id])  #レコードを1件だけ取得するので、インスタンス変数名は単数形の「@item」にする。
  end

  def  edit
    @item = Item.find(params[:id])  #レコードを1件だけ取得するので、インスタンス変数名は単数形の「@item」にする。
  end


  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path(item.id)
  end



private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h1>商品編集画面(admin/items/edit)ページ</h1>


<%= form_with model: @item, url: admin_edit_item_path(@item.id), method: :patch do |f| %>


  <h4>商品名</h4>
    <%= f.text_field :name %>


  <h4>商品説明</h4>
    <%= f.text_area :introduction %>


  <h4>税抜き価格</h4>
    <%= f.text_field :price %> 円


  <%= f.submit '保存' %>

<% end %>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>

<% @items.each do |item| %>

  <p>商品名</p>
    <span>
      <%= link_to item.name, admin_item_path(item.id) %>
    </span>


<% end %>

app/views/admin/items/new.html.erb
<h1>商品新規投稿画面</h1>

  <%= form_with model: @item, url: admin_items_path do |f| %>

    <h1>商品名</h1>
      <%= f.text_field :name %>

    <h1>商品説明文</h1>
      <%= f.text_area :introduction %>

    <h1>税抜き価格</h1>
      <%= f.text_field :price %> 円



    <%= f.submit '投稿' %>
  <% end %>

app/views/admin/items/show.html.erb
<h1>商品詳細(admin/items/show)ページ</h1>

<p>
  <%= @item.name %>
</p>


<h4>
  商品説明
</h4>
<p>
  <%= @item.introduction %>
</p>


 <h4>
   税抜き価格
 </h4>
 <p>
    <%= @item.price %> 円
 </p>


<%= link_to "商品編集画面", edit_admin_item_path(@item.id) %>