config/routes.rb
Rails.application.routes.draw do




#顧客用
#URL  /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

    scope module: :public do
      root to: "homes#top"
      get 'about' => 'homes#about'
      resources :items, only: [:index, :show]
      resources :customers, only: [:show, :edit, :update]

      resources :cart_items, only: [:index, :update, :create, :destroy]
      resources :orders, only: [:new, :index, :show]
    end







#管理者側
#URL  /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

    namespace :admin do
      get '/' => 'homes#top'
      post 'items' => 'items#create'
      patch 'items/:id' => 'items#update',as: 'edit_item'
      resources :items, only: [:new, :index, :show, :edit]
      resources :customers, only: [:index, :show, :edit, :update]
    end




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cake2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if customer_signed_in? %>
        <li>
          <%= link_to "ログアウト(顧客)", destroy_customer_session_path,method: :delete %>
        </li>
        <li>
          <%= link_to "マイページ(顧客)", customer_path(current_customer.id) %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録(顧客)", new_customer_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン(顧客)", new_customer_session_path %>
        </li>
      <% end %>

      <% if admin_signed_in? %>
        <li>
          <%= link_to "ログアウト(管理者)", destroy_admin_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "ログイン(管理者)", new_admin_session_path %>
        </li>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>